In [74]:
import numpy as np
a=np.array([[1,2],[2,3],[0,0]]) #M=3, D=2
y=[1,2,2]

In [75]:
x_new=np.array([[1,0],[1,1],[1,2]])

In [6]:
x_new

array([[1, 0],
       [1, 1]])

In [7]:
a

array([[1, 2],
       [2, 3],
       [0, 0]])

In [76]:
import math
p=1
first=True
k=3

for x in x_new:
   
    dist=np.sum(abs(x-a)**p, axis=1)**(1/p)
    
    if first:
        dist_matrix=dist
        first=False
        
    else:
        dist_matrix=np.vstack((dist_matrix,dist))
    indeces=np.argsort(dist)[:k]
    print(indeces)
print(dist_matrix)

[2 0 1]
[0 2 1]
[0 1 2]
[[2. 4. 1.]
 [1. 3. 2.]
 [0. 2. 3.]]


In [77]:
indeces=np.argsort(dist_matrix)[:,:3]

In [78]:
y=np.array(y)

In [79]:
classes=y[indeces]
classes[0][0]=0
classes

array([[0, 1, 2],
       [1, 2, 2],
       [1, 2, 2]])

In [80]:
for row in classes:
        counts=np.bincount(row)
        #print(f"counts{counts}")
        maxpos=counts.argmax()
        print(maxpos)

0
2
2


In [45]:
unique,pos = np.unique(classes,return_inverse=True) 

In [64]:
w=np.ones(classes.shape)

In [62]:
classes=classes.ravel()
classes

array([1, 0, 1, 0, 1, 1, 0, 1, 1])

In [65]:
counts=np.bincount(classes)

In [67]:
unique,pos = np.unique(classes,return_inverse=True) 
unique

array([0, 1])

In [68]:
pos

array([1, 0, 1, 0, 1, 1, 0, 1, 1], dtype=int64)

In [86]:
y=[3, 1 , 3, 0, 2]
np.bincount(y).argmax()

3